---
name: Test & release

'on':
  - pull_request
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}',
                          github.event.repository.default_branch) }}

jobs:
  should-run:
    name: Prep / Should run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should-run: ${{ steps.action.outputs.should-run }}
    steps:
      - id: action
        # yamllint disable-line rule:line-length
        uses: techneg-it/should-workflow-run@eff19348eb884f57e05bc6f05ae48ece3af14714 # v1.0.1
  pre-commit:
    name: Lint / `pre-commit`
    needs: should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    container: techneg/ci-pre-commit:v2.5.58@sha256:56e0bf7d16560020b738a2378240643ccb399350a540e906ca1e27009ffe2d68
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: | # Needed because of bug #2031 in `actions/checkout`
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
          filter: tree:0
      - name: Export `CI_CACHE_ID` from container
        run: echo "CI_CACHE_ID=$(cat /.ci_cache_id)" >> $GITHUB_ENV
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: "${{ env.CI_CACHE_ID }}|\
                ${{ hashFiles('.pre-commit-config.yaml') }}"
          restore-keys: |
            ${{ env.CI_CACHE_ID }}|
      - name: Build cache
        run: |
          pre-commit gc
          echo "Installing hook environments..."
          time -f "Hook installation took %E" pre-commit install-hooks
      - name: Run `pre-commit`
        run: |
          pre-commit run --all-files --color always --verbose
          pre-commit run --color always --hook-stage manual --verbose commitlint-ci
  results:
    name: Release / Collect results
    permissions:
      contents: write
      issues: write
      pull-requests: write
      checks: read
    container: techneg/ci-semantic-release:v1.2.58@sha256:723edbddfa534c7c137f09adec5fb2dfd6286d3fcb9c63688d7e5265ca4dd77e
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: |  # Needed due to bug actions/checkout#2031
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # yamllint disable-line rule:line-length
      - uses: poseidon/wait-for-status-checks@e7e24423722c5b8e97a6dd5848827d2a412f812d # v0.7.0
        with:
          ignore: >
            Dependabot,
            Release / Collect results,
          ignore_pattern: ^GitLab CI
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run `semantic-release`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAINTAINER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release --dry-run
      - run: echo "::notice ::Workflow success!"
